TRAIN_DATA_1 = [
    ("queen bed frames.", {"entities": [(0, 16, "PRODUCT")]}),
    ("double bed frames.", {"entities": [(0, 17, "PRODUCT")]}),
    ("king bed frames.", {"entities": [(0, 15, "PRODUCT")]}),
    ("single bed frames.", {"entities": [(0, 17, "PRODUCT")]}),
    ("king single bed frames.", {"entities": [(0, 22, "PRODUCT")]}),
    ("chairs.", {"entities": [(0, 6, "PRODUCT")]}),
    ("sofas.", {"entities": [(0, 5, "PRODUCT")]}),
    ("armchairs.", {"entities": [(0, 9, "PRODUCT")]}),
    ("dining chairs.", {"entities": [(0, 13, "PRODUCT")]}),
    ("bar stools.", {"entities": [(0, 10, "PRODUCT")]}),
    ("bunk beds.", {"entities": [(0, 9, "PRODUCT")]}),
    ("office chairs.", {"entities": [(0, 13, "PRODUCT")]}),
    ("lounge chairs.", {"entities": [(0, 13, "PRODUCT")]}),
    ("patio chairs.", {"entities": [(0, 12, "PRODUCT")]}),
    ("bean bags.", {"entities": [(0, 9, "PRODUCT")]}),
    ("ottomans.", {"entities": [(0, 8, "PRODUCT")]}),
    ("daybeds.", {"entities": [(0, 7, "PRODUCT")]}),
    ("futons.", {"entities": [(0, 6, "PRODUCT")]}),
    ("recliners.", {"entities": [(0, 9, "PRODUCT")]}),
    ("loveseats.", {"entities": [(0, 9, "PRODUCT")]}),
    ("sectional sofas.", {"entities": [(0, 15, "PRODUCT")]}),
    ("accent chairs.", {"entities": [(0, 13, "PRODUCT")]}),
    ("rocking chairs.", {"entities": [(0, 14, "PRODUCT")]}),
    ("swing chairs.", {"entities": [(0, 12, "PRODUCT")]}),
    ("adirondack chairs.", {"entities": [(0, 17, "PRODUCT")]}),
    ("couches.", {"entities": [(0, 7, "PRODUCT")]}),
    ("vanities.", {"entities": [(0, 8, "PRODUCT")]}),
    ("dressing tables.", {"entities": [(0, 15, "PRODUCT")]}),
    ("console tables.", {"entities": [(0, 14, "PRODUCT")]}),
    ("end tables.", {"entities": [(0, 10, "PRODUCT")]}),
    ("coffee tables.", {"entities": [(0, 13, "PRODUCT")]}),
    ("nightstands.", {"entities": [(0, 11, "PRODUCT")]}),
    ("desks.", {"entities": [(0, 5, "PRODUCT")]}),
    ("bookcases.", {"entities": [(0, 9, "PRODUCT")]}),
    ("shelving units.", {"entities": [(0, 14, "PRODUCT")]}),
    ("wardrobes.", {"entities": [(0, 9, "PRODUCT")]}),
    ("dressers.", {"entities": [(0, 8, "PRODUCT")]}),
    ("chest of drawers.", {"entities": [(0, 16, "PRODUCT")]}),
    ("mirrors.", {"entities": [(0, 7, "PRODUCT")]}),
    ("rug.", {"entities": [(0, 3, "PRODUCT")]}),
    ("table lamps.", {"entities": [(0, 11, "PRODUCT")]}),
    ("floor lamps.", {"entities": [(0, 11, "PRODUCT")]}),
    ("ceiling lights.", {"entities": [(0, 14, "PRODUCT")]}),
    ("pendant lights.", {"entities": [(0, 14, "PRODUCT")]}),
    ("chandeliers.", {"entities": [(0, 11, "PRODUCT")]}),
    ("wall sconces.", {"entities": [(0, 12, "PRODUCT")]}),
    ("desk lamps.", {"entities": [(0, 10, "PRODUCT")]}),
    ("bathroom vanities.", {"entities": [(0, 17, "PRODUCT")]}),
    ("bathroom mirrors.", {"entities": [(0, 16, "PRODUCT")]}),
    ("shower curtains.", {"entities": [(0, 15, "PRODUCT")]}),
    ("towels.", {"entities": [(0, 6, "PRODUCT")]}),
    ("bath mats.", {"entities": [(0, 9, "PRODUCT")]}),
    ("toilet paper holders.", {"entities": [(0, 20, "PRODUCT")]}),
    ("soap dispensers.", {"entities": [(0, 15, "PRODUCT")]}),
    ("toothbrush holders.", {"entities": [(0, 18, "PRODUCT")]}),
    ("trash cans.", {"entities": [(0, 10, "PRODUCT")]}),
    ("laundry baskets.", {"entities": [(0, 15, "PRODUCT")]}),
    ("storage bins.", {"entities": [(0, 12, "PRODUCT")]}),
    ("jewelry organizers.", {"entities": [(0, 18, "PRODUCT")]}),
    ("kitchen islands.", {"entities": [(0, 15, "PRODUCT")]}),
    ("bar carts.", {"entities": [(0, 9, "PRODUCT")]}),
    ("wine racks.", {"entities": [(0, 10, "PRODUCT")]}),
    ("kitchen utensil holders.", {"entities": [(0, 23, "PRODUCT")]}),
    ("spice racks.", {"entities": [(0, 11, "PRODUCT")]}),
    ("cutting boards.", {"entities": [(0, 14, "PRODUCT")]}),
    ("kitchen towels.", {"entities": [(0, 14, "PRODUCT")]}),
    ("pot racks.", {"entities": [(0, 9, "PRODUCT")]}),
    ("mixing bowls.", {"entities": [(0, 12, "PRODUCT")]}),
    ("food storage containers.", {"entities": [(0, 23, "PRODUCT")]}),
    ("baking sheets.", {"entities": [(0, 13, "PRODUCT")]}),
    ("cookware sets.", {"entities": [(0, 13, "PRODUCT")]}),
    ("knife sets.", {"entities": [(0, 10, "PRODUCT")]}),
    ("kitchen scales.", {"entities": [(0, 14, "PRODUCT")]}),
    ("blenders.", {"entities": [(0, 8, "PRODUCT")]}),
    ("coffee makers.", {"entities": [(0, 13, "PRODUCT")]}),
    ("toasters.", {"entities": [(0, 8, "PRODUCT")]}),
    ("food processors.", {"entities": [(0, 15, "PRODUCT")]}),
    ("juicers.", {"entities": [(0, 7, "PRODUCT")]}),
    ("stand mixers.", {"entities": [(0, 12, "PRODUCT")]}),
    ("microwaves.", {"entities": [(0, 10, "PRODUCT")]}),
    ("air fryers.", {"entities": [(0, 10, "PRODUCT")]}),
    ("pressure cookers.", {"entities": [(0, 16, "PRODUCT")]}),
    ("slow cookers.", {"entities": [(0, 12, "PRODUCT")]}),
    ("electric kettles.", {"entities": [(0, 16, "PRODUCT")]}),
    ("wine glasses.", {"entities": [(0, 12, "PRODUCT")]}),
    ("beer glasses.", {"entities": [(0, 12, "PRODUCT")]}),
    ("cocktail glasses.", {"entities": [(0, 16, "PRODUCT")]}),
    ("shot glasses.", {"entities": [(0, 12, "PRODUCT")]}),
    ("whiskey glasses.", {"entities": [(0, 15, "PRODUCT")]}),
    ("champagne flutes.", {"entities": [(0, 16, "PRODUCT")]}),
    ("margarita glasses.", {"entities": [(0, 17, "PRODUCT")]}),
    ("martini glasses.", {"entities": [(0, 15, "PRODUCT")]}),
    ("decanters.", {"entities": [(0, 9, "PRODUCT")]}),
    ("wine openers.", {"entities": [(0, 12, "PRODUCT")]}),
    ("corkscrews.", {"entities": [(0, 10, "PRODUCT")]}),
    ("wine stoppers.", {"entities": [(0, 13, "PRODUCT")]}),
    ("wine racks.", {"entities": [(0, 10, "PRODUCT")]}),
    ("wine aerators.", {"entities": [(0, 13, "PRODUCT")]}),
    ("wine preservers.", {"entities": [(0, 15, "PRODUCT")]}),
    ("wine pourers.", {"entities": [(0, 12, "PRODUCT")]}),
    ("wine chillers.", {"entities": [(0, 13, "PRODUCT")]}),
    ("wine coasters.", {"entities": [(0, 13, "PRODUCT")]}),
    ("wine thermometers.", {"entities": [(0, 17, "PRODUCT")]}),
    ("wine gift sets.", {"entities": [(0, 14, "PRODUCT")]}),
    ("wine decanters.", {"entities": [(0, 14, "PRODUCT")]}),
]


TRAIN_DATA_2 = [
    ("Check out our selection of futons.", {"entities": [(27, 33, "PRODUCT")]}),
    ("Discover our collection of chaise lounges.", {"entities": [(27, 41, "PRODUCT")]}),
    ("Upgrade your workspace with our ergonomic standing desks.", {"entities": [(42, 56, "PRODUCT")]}),
    ("Find the perfect vanity mirror for your makeup station.", {"entities": [(17, 30, "PRODUCT")]}),
    ("Browse through our selection of bean bag chairs.", {"entities": [(32, 47, "PRODUCT")]}),
    ("Explore our range of hammocks for ultimate relaxation.", {"entities": [(21, 29, "PRODUCT")]}),
    ("Revamp your dining area with our modern dining tables.", {"entities": [(33, 53, "PRODUCT")]}),
    ("Create a cozy reading nook with our papasan chairs.", {"entities": [(36, 50, "PRODUCT")]}),
    ("Upgrade your outdoor space with our patio umbrellas.", {"entities": [(36, 51, "PRODUCT")]}),
    ("Add elegance to your bedroom with our canopy beds.", {"entities": [(38, 49, "PRODUCT")]}),
    ("Enhance your living room with our reclining sofas.", {"entities": [(34, 49, "PRODUCT")]}),
    ("Maximize space with our versatile storage ottomans.", {"entities": [(42, 51, "PRODUCT")]}),
    ("Organize your shoes with our stylish shoe racks.", {"entities": [(29, 47, "PRODUCT")]}),
    ("Elevate your workspace with our adjustable office desks.", {"entities": [(32, 55, "PRODUCT")]}),
    ("Upgrade your dining experience with our counter-height tables.", {"entities": [(40, 61, "PRODUCT")]}),
    ("Add a touch of luxury with our velvet accent chairs.", {"entities": [(31, 51, "PRODUCT")]}),
    ("Enjoy cozy nights with our electric fireplace inserts.", {"entities": [(27, 53, "PRODUCT")]}),
    ("Transform your patio with our outdoor lounge chairs.", {"entities": [(30, 51, "PRODUCT")]}),
    ("Create a spa-like atmosphere with our bamboo bath mats.", {"entities": [(38, 54, "PRODUCT")]}),
    ("Add charm to your garden with our decorative bird baths.", {"entities": [(34, 55, "PRODUCT")]}),
    ("Organize your kitchen with our wall-mounted spice racks.", {"entities": [(31, 55, "PRODUCT")]}),
    ("Upgrade your cooking experience with our non-stick cookware sets.", {"entities": [(41, 64, "PRODUCT")]}),
    ("Create a cozy atmosphere with our flameless LED candles.", {"entities": [(34, 55, "PRODUCT")]}),
    ("Maximize comfort with our memory foam mattress toppers.", {"entities": [(26, 54, "PRODUCT")]}),
    ("Enhance your dining room with our farmhouse-style dining benches.", {"entities": [(34, 64, "PRODUCT")]}),
    ("Add elegance to your living space with our crystal chandeliers.", {"entities": [(43, 62, "PRODUCT")]}),
    ("Organize your entryway with our wall-mounted coat racks.", {"entities": [(32, 55, "PRODUCT")]}),
    ("Upgrade your home theater with our leather home theater seating.", {"entities": [(35, 63, "PRODUCT")]}),
    ("Create a cozy corner with our overstuffed armchairs.", {"entities": [(30, 51, "PRODUCT")]}),
    ("Transform your backyard with our outdoor fire pits.", {"entities": [(33, 50, "PRODUCT")]}),
    ("Upgrade your workspace with our height-adjustable standing desks.", {"entities": [(32, 64, "PRODUCT")]}),
    ("Add functionality to your bathroom with our wall-mounted towel racks.", {"entities": [(44, 68, "PRODUCT")]}),
    ("Organize your pantry with our stackable storage containers.", {"entities": [(30, 58, "PRODUCT")]}),
    ("Enhance your outdoor space with our solar-powered garden lights.", {"entities": [(36, 63, "PRODUCT")]}),
    ("Create a cozy ambiance with our Himalayan salt lamps.", {"entities": [(32, 52, "PRODUCT")]}),
    ("Upgrade your kitchen with our stainless steel knife sets.", {"entities": [(30, 56, "PRODUCT")]}),
    ("Add elegance to your dining room with our upholstered dining chairs.", {"entities": [(42, 67, "PRODUCT")]}),
    ("Organize your closet with our space-saving hangers.", {"entities": [(30, 50, "PRODUCT")]}),
    ("Enhance your outdoor gatherings with our portable ice makers.", {"entities": [(41, 60, "PRODUCT")]}),
    ("Create a relaxing retreat with our aromatherapy essential oil diffusers.", {"entities": [(35, 71, "PRODUCT")]}),
    ("Upgrade your bathroom with our rainfall shower heads.", {"entities": [(31, 52, "PRODUCT")]}),
    ("Add charm to your garden with our ceramic garden stools.", {"entities": [(34, 55, "PRODUCT")]}),
    ("Organize your workspace with our desktop file organizers.", {"entities": [(33, 56, "PRODUCT")]}),
    ("Enhance your bedroom with our luxurious silk pillowcases.", {"entities": [(30, 56, "PRODUCT")]}),
    ("Create a cozy reading nook with our adjustable floor lamps.", {"entities": [(36, 58, "PRODUCT")]}),
    ("Upgrade your living room with our modular sectional sofas.", {"entities": [(34, 57, "PRODUCT")]}),
    ("Add elegance to your dining experience with our fine china dinnerware sets.", {"entities": [(48, 74, "PRODUCT")]}),
    ("Organize your home office with our wire mesh desk organizers.", {"entities": [(35, 60, "PRODUCT")]}),
    ("Enhance your outdoor seating with our weather-resistant patio cushions.", {"entities": [(38, 70, "PRODUCT")]}),
    ("Create a spa-like bathroom with our plush bath towel sets.", {"entities": [(36, 57, "PRODUCT")]}),
    ("Upgrade your kitchen tools with our professional chef's knives.", {"entities": [(36, 62, "PRODUCT")]}),
    ("Add charm to your garden with our whimsical garden gnomes.", {"entities": [(34, 57, "PRODUCT")]}),
    ("Organize your closet with our space-saving shoe storage racks.", {"entities": [(30, 61, "PRODUCT")]}),
    ("Enhance your outdoor space with our decorative solar garden stakes.", {"entities": [(36, 67, "PRODUCT")]}),
    ("Create a cozy ambiance with our flameless LED pillar candles.", {"entities": [(32, 60, "PRODUCT")]}),
    ("Upgrade your bedroom with our premium memory foam mattress.", {"entities": [(30, 58, "PRODUCT")]}),
    ("Add elegance to your dining room with our upholstered dining benches.", {"entities": [(42, 68, "PRODUCT")]}),
    ("Organize your pantry with our stackable airtight food storage containers.", {"entities": [(30, 72, "PRODUCT")]}),
    ("Enhance your outdoor gatherings with our portable Bluetooth speakers.", {"entities": [(41, 68, "PRODUCT")]}),
    ("Create a relaxing retreat with our plush microfiber bath robes.", {"entities": [(35, 62, "PRODUCT")]}),
    ("Upgrade your bathroom with our luxurious rainfall shower system.", {"entities": [(31, 63, "PRODUCT")]}),
    ("Add charm to your garden with our decorative outdoor string lights.", {"entities": [(34, 66, "PRODUCT")]}),
    ("Organize your workspace with our modern desk accessories.", {"entities": [(33, 56, "PRODUCT")]}),
    ("Enhance your bedroom with our stylish upholstered headboards.", {"entities": [(30, 60, "PRODUCT")]}),
    ("Create a cozy reading nook with our adjustable floor reading lamps.", {"entities": [(36, 66, "PRODUCT")]}),
    ("Upgrade your living room with our sleek leather reclining sofas.", {"entities": [(34, 63, "PRODUCT")]}),
    ("Add elegance to your dining experience with our fine bone china dinnerware sets.", {"entities": [(48, 79, "PRODUCT")]}),
    ("Organize your home office with our stylish desk organizers.", {"entities": [(35, 58, "PRODUCT")]}),
    ("Enhance your outdoor seating with our comfortable patio lounge chairs.", {"entities": [(50, 69, "PRODUCT")]}),
    ("Create a spa-like bathroom with our soft Egyptian cotton bath towels.", {"entities": [(36, 68, "PRODUCT")]}),
    ("Upgrade your kitchen tools with our professional-grade chef's knives.", {"entities": [(36, 68, "PRODUCT")]}),
    ("Add charm to your garden with our decorative ceramic planters.", {"entities": [(34, 61, "PRODUCT")]}),
    ("Organize your closet with our versatile hanging closet organizers.", {"entities": [(30, 65, "PRODUCT")]}),
    ("Enhance your outdoor space with our durable aluminum patio furniture.", {"entities": [(36, 68, "PRODUCT")]}),
    ("Create a cozy ambiance with our scented soy wax candles.", {"entities": [(32, 55, "PRODUCT")]}),
    ("Upgrade your bedroom with our luxurious Egyptian cotton bed sheets.", {"entities": [(30, 66, "PRODUCT")]}),
    ("Add elegance to your dining room with our classic farmhouse dining tables.", {"entities": [(42, 73, "PRODUCT")]}),
    ("Organize your pantry with our convenient stackable pantry organizers.", {"entities": [(30, 68, "PRODUCT")]}),
    ("Enhance your outdoor gatherings with our portable outdoor gas fire pits.", {"entities": [(41, 71, "PRODUCT")]}),
    ("Create a relaxing retreat with our soft microfiber bed comforter sets.", {"entities": [(35, 69, "PRODUCT")]}),
    ("Upgrade your bathroom with our luxurious rainfall shower head system.", {"entities": [(31, 68, "PRODUCT")]}),
    ("Add charm to your garden with our decorative solar-powered garden lights.", {"entities": [(34, 72, "PRODUCT")]}),
    ("Organize your workspace with our versatile desktop file organizers.", {"entities": [(33, 66, "PRODUCT")]}),
    ("Enhance your bedroom with our cozy down alternative comforters.", {"entities": [(30, 62, "PRODUCT")]}),
    ("Create a cozy reading nook with our adjustable LED floor reading lamps.", {"entities": [(36, 70, "PRODUCT")]}),
    ("Upgrade your living room with our comfortable fabric reclining sofas.", {"entities": [(34, 69, "PRODUCT")]}),
    ("Add elegance to your dining experience with our premium bone china dinnerware sets.", {"entities": [(48, 82, "PRODUCT")]}),
    ("Organize your home office with our stylish wire mesh desk organizers.", {"entities": [(35, 68, "PRODUCT")]}),
    ("Enhance your outdoor seating with our durable weather-resistant patio dining sets.", {"entities": [(38, 81, "PRODUCT")]}),
    ("Create a spa-like bathroom with our luxurious Turkish cotton bath towels.", {"entities": [(36, 72, "PRODUCT")]}),
    ("Upgrade your kitchen tools with our professional-grade stainless steel chef's knives.", {"entities": [(36, 84, "PRODUCT")]}),
    ("Add charm to your garden with our decorative metal garden trellises.", {"entities": [(34, 67, "PRODUCT")]}),
    ("Organize your closet with our space-saving over-the-door shoe organizers.", {"entities": [(30, 72, "PRODUCT")]}),
    ("Enhance your outdoor space with our stylish solar-powered outdoor string lights.", {"entities": [(36, 79, "PRODUCT")]}),
    ("Create a cozy ambiance with our scented soy wax votive candles.", {"entities": [(32, 62, "PRODUCT")]}),
    ("Upgrade your bedroom with our luxurious silk satin bed sheet sets.", {"entities": [(30, 65, "PRODUCT")]}),
    ("Add elegance to your dining room with our classic farmhouse-style dining chairs.", {"entities": [(42, 79, "PRODUCT")]}),
    ("Organize your pantry with our convenient stackable plastic pantry organizers.", {"entities": [(30, 76, "PRODUCT")]}),
    ("Enhance your outdoor gatherings with our portable Bluetooth waterproof speakers.", {"entities": [(41, 79, "PRODUCT")]}),
    ("Create a relaxing retreat with our soft hypoallergenic down alternative pillows.", {"entities": [(35, 79, "PRODUCT")]}),
    ("Upgrade your bathroom with our luxurious rainfall shower head and handheld combo.", {"entities": [(31, 80, "PRODUCT")]}),
    ("Add charm to your garden with our decorative resin outdoor garden fountains.", {"entities": [(34, 75, "PRODUCT")]}),
    ("Organize your workspace with our versatile wall-mounted floating desk shelves.", {"entities": [(33, 77, "PRODUCT")]}),
    ("Enhance your bedroom with our cozy flannel fleece bed blanket throws.", {"entities": [(30, 68, "PRODUCT")]}),
]

TRAIN_DATA_3 = [
    ("Upgrade your living room with our leather reclining sofas and modern coffee tables.", {"entities": [(34, 57, "PRODUCT"), (62, 82, "PRODUCT")]}),
    ("Add style to your bedroom with our upholstered platform beds and sleek nightstands.", {"entities": [(35, 60, "PRODUCT"), (65, 82, "PRODUCT")]}),
    ("Organize your kitchen with our adjustable pot racks and compact spice organizers.", {"entities": [(31, 51, "PRODUCT"), (56, 80, "PRODUCT")]}),
    ("Enhance your outdoor space with our wooden Adirondack chairs and cozy hammocks.", {"entities": [(36, 60, "PRODUCT"), (65, 78, "PRODUCT")]}),
    ("Create a cozy reading nook with our bean bag chairs and adjustable reading lamps.", {"entities": [(36, 51, "PRODUCT"), (56, 80, "PRODUCT")]}),
    ("Upgrade your dining area with our glass-top dining tables and modern dining chairs.", {"entities": [(34, 57, "PRODUCT"), (62, 82, "PRODUCT")]}),
    ("Add comfort to your patio with our cushioned outdoor loveseats and rattan coffee tables.", {"entities": [(35, 62, "PRODUCT"), (67, 87, "PRODUCT")]}),
    ("Organize your closet with our shoe storage benches and hanging shoe organizers.", {"entities": [(30, 50, "PRODUCT"), (55, 78, "PRODUCT")]}),
    ("Enhance your workspace with our ergonomic office chairs and adjustable standing desks.", {"entities": [(32, 55, "PRODUCT"), (60, 85, "PRODUCT")]}),
    ("Create a cozy corner with our sectional sleeper sofas and oversized floor pillows.", {"entities": [(30, 53, "PRODUCT"), (58, 81, "PRODUCT")]}),
    ("Upgrade your outdoor living space with our wicker patio sets and outdoor umbrellas.", {"entities": [(43, 60, "PRODUCT"), (65, 82, "PRODUCT")]}),
    ("Add elegance to your bedroom with our canopy bed frames and luxurious bedding sets.", {"entities": [(38, 55, "PRODUCT"), (60, 82, "PRODUCT")]}),
    ("Organize your home office with our floating wall shelves and stylish desk organizers.", {"entities": [(35, 56, "PRODUCT"), (61, 84, "PRODUCT")]}),
    ("Enhance your patio with our outdoor sectional sofas and fire pit dining tables.", {"entities": [(28, 51, "PRODUCT"), (56, 78, "PRODUCT")]}),
    ("Create a cozy retreat with our upholstered chaise lounges and plush throw blankets.", {"entities": [(31, 57, "PRODUCT"), (62, 82, "PRODUCT")]}),
    ("Upgrade your dining experience with our marble-top dining tables and upholstered benches.", {"entities": [(40, 64, "PRODUCT"), (69, 88, "PRODUCT")]}),
    ("Add functionality to your workspace with our rolling file cabinets and corner desks.", {"entities": [(45, 66, "PRODUCT"), (71, 83, "PRODUCT")]}),
    ("Organize your entryway with our hall trees and shoe storage benches.", {"entities": [(32, 42, "PRODUCT"), (47, 67, "PRODUCT")]}),
    ("Enhance your outdoor relaxation with our hanging swing chairs and outdoor lounge beds.", {"entities": [(41, 61, "PRODUCT"), (66, 85, "PRODUCT")]}),
    ("Create a cozy nook with our papasan chairs and bohemian floor cushions.", {"entities": [(28, 42, "PRODUCT"), (47, 70, "PRODUCT")]}),
    ("Upgrade your home theater with our reclining theater chairs and entertainment centers.", {"entities": [(35, 59, "PRODUCT"), (64, 85, "PRODUCT")]}),
    ("Add elegance to your bedroom with our tufted headboards and matching nightstands.", {"entities": [(38, 55, "PRODUCT"), (60, 80, "PRODUCT")]}),
    ("Organize your garage with our heavy-duty shelving units and tool storage cabinets.", {"entities": [(30, 55, "PRODUCT"), (60, 81, "PRODUCT")]}),
    ("Enhance your outdoor dining with our teak patio tables and weatherproof dining chairs.", {"entities": [(37, 54, "PRODUCT"), (59, 85, "PRODUCT")]}),
    ("Create a cozy ambiance with our electric fireplaces and decorative wall mirrors.", {"entities": [(32, 51, "PRODUCT"), (56, 79, "PRODUCT")]}),
    ("Upgrade your living space with our modular sectional sofas and contemporary rugs.", {"entities": [(35, 58, "PRODUCT"), (63, 80, "PRODUCT")]}),
    ("Add charm to your garden with our cast iron garden benches and whimsical bird feeders.", {"entities": [(34, 58, "PRODUCT"), (63, 85, "PRODUCT")]}),
    ("Organize your pantry with our pull-out pantry shelves and stackable food containers.", {"entities": [(39, 53, "PRODUCT"), (58, 83, "PRODUCT")]}),
    ("Enhance your outdoor gathering with our outdoor bar sets and portable beverage coolers.", {"entities": [(40, 56, "PRODUCT"), (61, 86, "PRODUCT")]}),
    ("Create a cozy reading spot with our wingback reading chairs and adjustable reading lamps.", {"entities": [(36, 59, "PRODUCT"), (64, 88, "PRODUCT")]}),
    ("Upgrade your dining area with our marble-top dining tables and velvet dining chairs.", {"entities": [(34, 58, "PRODUCT"), (63, 83 , "PRODUCT")]}),
    ("Create a relaxing retreat with our soft robes and diffusers.", {"entities": [(35, 45, "PRODUCT"), (50, 59, "PRODUCT")]}),
    ("Upgrade your bathroom with our shower heads and towels.", {"entities": [(31, 43, "PRODUCT"), (48, 54, "PRODUCT")]}),
    ("Add charm to your garden with our fountains and lights.", {"entities": [(34, 43, "PRODUCT"), (48, 54, "PRODUCT")]}),
    ("Organize your workspace with our organizers and holders.", {"entities": [(33, 43, "PRODUCT"), (48, 55, "PRODUCT")]}),
    ("Enhance your bedroom with our blankets and toppers.", {"entities": [(30, 38, "PRODUCT"), (43, 50, "PRODUCT")]}),
    ("Create a cozy reading nook with our lamps and chairs.", {"entities": [(56, 41, "PRODUCT"), (46, 52, "PRODUCT")]}),
    ("Upgrade your living room with our sofas and tables.", {"entities": [(34, 39, "PRODUCT"), (44, 50, "PRODUCT")]}),
    ("Add elegance to your dining experience with our sets and glasses.", {"entities": [(48, 52, "PRODUCT"), (57, 64, "PRODUCT")]}),
    ("Organize your home office with our organizers and trays.", {"entities": [(35, 45, "PRODUCT"), (50, 55, "PRODUCT")]}),
    ("Enhance your outdoor seating with our sets and chairs.", {"entities": [(38, 42, "PRODUCT"), (47, 53, "PRODUCT")]}),
    ("Create a spa-like bathroom with our towels and mats.", {"entities": [(36, 42, "PRODUCT"), (47, 51, "PRODUCT")]}),
    ("Upgrade your kitchen tools with our knives and sets.", {"entities": [(36, 42, "PRODUCT"), (47, 51, "PRODUCT")]}),
    ("Add charm to your garden with our stools and lights.", {"entities": [(34, 40, "PRODUCT"), (45, 51, "PRODUCT")]}),
    ("Organize your closet with our racks and boxes.", {"entities": [(30, 35, "PRODUCT"), (40, 45, "PRODUCT")]}),
    ("Enhance your outdoor space with our lights and planters.", {"entities": [(36, 42, "PRODUCT"), (47, 55, "PRODUCT")]}),
    ("Create a cozy ambiance with our candles and lamps.", {"entities": [(32, 39, "PRODUCT"), (44, 49, "PRODUCT")]}),
    ("Upgrade your bedroom with our pillowcases and comforters.", {"entities": [(30, 41, "PRODUCT"), (46, 56, "PRODUCT")]}),
    ("Add elegance to your dining room with our benches and tables.", {"entities": [(42, 49, "PRODUCT"), (54, 60, "PRODUCT")]}),
    ("Organize your pantry with our containers and baskets.", {"entities": [(30, 40, "PRODUCT"), (45, 52, "PRODUCT")]}),
    ("Enhance your outdoor gatherings with our speakers and fire pits.", {"entities": [(41, 49, "PRODUCT"), (54, 63, "PRODUCT")]}),
    ("Refresh your bedroom with our linen duvet covers and down pillows.", {"entities": [(30, 48, "PRODUCT"), (53, 65, "PRODUCT")]}),
    ("Upgrade your kitchen with our copper cookware sets and silicone utensils.", {"entities": [(30, 50, "PRODUCT"), (55, 72, "PRODUCT")]}),
    ("Organize your bathroom with our bamboo bath mats and acrylic shower caddies.", {"entities": [(32, 48, "PRODUCT"), (53, 75, "PRODUCT")]}),
    ("Enhance your living room with our leather recliner sofas and glass side tables.", {"entities": [(34, 56, "PRODUCT"), (61, 78, "PRODUCT")]}),
    ("Create a cozy reading nook with our bean bag chairs and adjustable floor lamps.", {"entities": [(36, 51, "PRODUCT"), (56, 78, "PRODUCT")]}),
    ("Transform your backyard with our wooden patio furniture sets and outdoor fire pits.", {"entities": [(33, 60, "PRODUCT"), (65, 82, "PRODUCT")]}),
    ("Upgrade your office space with our ergonomic standing desks and mesh office chairs.", {"entities": [(35, 59, "PRODUCT"), (64, 82, "PRODUCT")]}),
    ("Add charm to your garden with our wrought iron garden benches and ceramic planters.", {"entities": [(34, 61, "PRODUCT"), (66, 82, "PRODUCT")]}),
    ("Organize your closet with our velvet hangers and stackable storage bins.", {"entities": [(37, 44, "PRODUCT"), (49, 71, "PRODUCT")]}),
    ("Enhance your outdoor space with our hammock swings and rattan lounge chairs.", {"entities": [(36, 50, "PRODUCT"), (55, 75, "PRODUCT")]}),
    ("Create a spa-like bathroom with our plush bath robes and bamboo bath trays.", {"entities": [(36, 52, "PRODUCT"), (57, 74, "PRODUCT")]}),
    ("Organize your bathroom with our bamboo bath caddies and ceramic soap dispensers.", {"entities": [(32, 51, "PRODUCT"), (56, 79, "PRODUCT")]}),
    ("Enhance your living room with our sectional sofas and marble coffee tables.", {"entities": [(34, 49, "PRODUCT"), (54, 74, "PRODUCT")]}),
]


TRAIN_DATA = TRAIN_DATA_1 + TRAIN_DATA_2 + TRAIN_DATA_3
